language: php
php:
- 5.6
node_js:
- '0.12'
env:
  global:
  - GIT_NAME: "'Couscous auto deploy'"
  - GIT_EMAIL: d.negrier@thecodingmachine.com
  - GH_REF: github.com/thecodingmachine/best-practices
  - secure: ONnVwIg1gp63GU/LBk4bzNMt1KfOORHsGlaUNaNNnyVBp/OmwJvc2ohm+McJOUrKLiHuTm0jkd4T0/DgOE7u14h7PXdzwG5R333y2lAsmslaFy6Whg3QXjLyiyV2kxHYR3Bc5aevMGp/cwQ9cVMytL2yycvAAiDI450kBX544zaC+SmktMM5ubZyEfkijxMTMm2tRoUrHROMBRE4/IItPgWFRIKYCj9d82I9Azn3WgbUrKutSf1xMa4wqtX+pSjKL90Yag1wq4K/IVf0z/spCT7rzNenGHXgO/FA2LevSfcssbm4xahD/X7mSKXMz0YEZbquyiXoj3J63aGRvdevxAEX0MnUthj+3EAEP5mJkbZmesnWBkgiKGzH++Wn0J4XTGC8Bl3Yv5cEp5Yu8LsZmSR3YlCNwbBG3XQdW8Y/MKfD/Jn+Lw4bzawpG1US2nV5SZG9Xz3hzaVlts+w+X8pR0Ne/QKTSmMFYNouMD4nMnAfoKSVD58lvkiIJZ2x4JqQUH6x8AP4hoLNO410s6wCHLYNEpSYt21PChekV/8LSDW9pNSrnovuM2AAzZ92HBA87xaYMFuJ557nVeU/Hw4oJK0WFBcSWKHZZRfGsOFTu/sGQzEvx621I56BvX8gwte43AfoncS79hhykLNsZg76qGPqOTVX2PzMhWgvARTUTt4=
before_script:
- composer install --no-progress
- npm install
- npm install -g bower
- npm install -g gulp
- bower install
- gulp
script:
- vendor/bin/couscous travis-auto-deploy --php-version=5.6
